import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./css/styles.css";
import "./css/normalize.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <link rel="canonical" href="https://www.sabibrowandbeauty.com/"></link>
      <title>
        SABI Brow & Beauty - Beauty Salon in Aurora, Naperville, Plainfield,
        Oswego
      </title>
      <meta
        name="description"
        content="Beauty Salon offering Eyebrow Threading, Waxing, Hair Removal, Eyelashes, Facial, Henna in Aurora, Naperville, Illinois. Affordable beauty services."
      />
      <meta
        property="og:title"
        content="Beauty Salon for Eyebrow Threading, Waxing, Hair removal, Eyelashes, Facial, Henna"
      />
      <meta
        property="og:description"
        content="Beauty Salon | Eyebrow Threading | Waxing | Hair removal | Eyelashes | Facial | Henna in Aurora, Naperville, Illinois"
      />
      <meta property="og:type" content="Website" />
      <meta property="og:image" content="assets/logo.png" />
      <meta property="og:url" content="http://sabibrowandbeauty.com" />
      <body>
        <NavBar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
